version: "3.3"
services:
  jenkins:
    image: "jenkins-docker:stable"
    ports: 
      - 8888:8080
      - 50000:50000
    volumes:
      - ./home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8192M
